### ISSUE TITLE
Port the account overlay from MirPromptSession to another option

### ISSUE THREAD

**Issue by UniversalSuperBox** [ubports/ubuntu-system-settings-online-accounts#11]
The [mir-helper](https://github.com/ubports/ubuntu-system-settings-online-accounts/blob/5de06385df2033675be6bbd0ccd11e895a7110a3/online-accounts-service/mir-helper.cpp) creates a MirPromptSession which is used to display the system-settings-online-accounts interface over the app that requested it. Even if that app is system-settings.

The MirPromptSession has no exact analog in the Wayland world. There is a similar enough specification in [xdg-foreign](https://github.com/wayland-project/wayland-protocols/blob/master/unstable/xdg-foreign/xdg-foreign-unstable-v2.xml). Support for this protocol must be added in QtMir, our Mir compositor, then the account overlay must be ported to use it.

Until this request is implemented, it is impossible to use system-settings-online-accounts on Wayland-using devices such as the PinePhone.

This issue is similar to https://github.com/ubports/trust-store/issues/7 and was filed for visibility. Fixing this issue closes https://gitlab.com/ubports/community-ports/pinephone/-/issues/42

**Comment by mozzwald** [comment]
Until this is properly fixed, is there a workaround to manually add an account? ie, add credentials from command line?

**Comment by Baggypants** [comment]
You can add accounts using `syncevolution`. There is a method for adding DAV accounts [Here](https://docs.ubports.com/en/latest/userguide/advanceduse/dav.html) I expect the provided script could be altered for [Google accounts](https://gist.github.com/bastos77/0c47a94dd0bf3e394f879c0ff42b7839#gistcomment-3321982).

**Comment by ghost** [comment]
That only works for calendar and contacts sync though. It works well, but it's not a solution for applications like uMarks and such.

It would probably be better for the time being to find out how to talk to `online-accounts-service` directy to add an account.

**Comment by ycharbi** [comment]
This problem is indeed blocking. A phone without contacts loses some of its interest. Luckily there is an alternative but it would be cool if it was possible to configure this directly from the settings application.

**Comment by mardy** [comment]
It shouldn't be too hard to implement a temporary option, where the `online-accounts-ui` process gets opened as an independent window. Unfortunately I'm not able to get QEMU to decently work, and I don't have a Pine phone to get into this work.

**Comment by UniversalSuperBox** [comment]
@mardy, I think if it worked on something that's not a PinePhone, it will likely work on the PinePhone too. So there's no need to have a PinePhone to try it out. I can test it for you if you need.

**Comment by ycharbi** [comment]
@mardy, me too. I have a PinePhone and I can test it for you if you need.

**Comment by talmage** [comment]
I also have a PinePhone.  I'm tracking the kernelupgrade channel.
