### ISSUE TITLE
Feature Request: requestAccess() complemet

### ISSUE THREAD

**Issue by belohoub** [ubports/ubuntu-system-settings-online-accounts#19]
I'm working on the new version of the UBsync app for Ubuntu Touch. In QML, I'm missing an API function allowing me to declare, that the (enabled) account should not be used by the app. 

Currently, removing access for an app is possible only from the system settings, so the application cannot handle complete account management and the user must switch to system settings to remove access to the account.

In my particular case, I use a hybrid model, where application-specific settings are stored in a "local" database and credentials are provided by signond. By "removing" the account from the application, I can only remove the application settings, but not the account access and by disabling account access in system settings, a configuration "stub" remains in my app db. No "complete" removal can be initiated by the app.

This is not a severe request, as the function is de-facto present, I'm just missing this feature to provide a complete feature set from the app itself.

Could you provide a complementary function to requestAccess() in the future to allow this in UbuntuTouch?

Best,

Jan

**Comment by UniversalSuperBox** [comment]
Hi, 

This request has been moved to GitLab. Please continue any discussion there: https://gitlab.com/ubports/core/lomiri-system-settings-online-accounts/-/issues/19
