### ISSUE TITLE
Add an Online Account, Untranslated

### ISSUE THREAD

**Issue by cibersheep** [ubports/ubuntu-system-settings-online-accounts#5]
Adding one of those online accounts, shows options not translated:
- Nextcloud
- Owncloud
- Generic CalDAV
- ownCloud

![imatge](https://user-images.githubusercontent.com/6640041/47595788-53d14680-d982-11e8-9807-8826b93c5c51.png)

**Comment by ghost** [comment]
Affected as well

**Comment by UniversalSuperBox** [comment]
Hi everyone,

This issue has been moved to GitLab. Please continue any discussion over there: https://gitlab.com/ubports/core/lomiri-system-settings-online-accounts/-/issues/5
